development:
  server: "https://drinkupchat.herokuapp.com/faye"
  secret_token: "secret"

test:
  server: "https://drinkupchat.herokuapp.com/faye"
  secret_token: "secret"

production:
  server: "https://drinkupchat.herokuapp.com/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
